// Modified from default app.js generated by couchapp,
// which is credit to 
//      Apache 2.0 J Chris Anderson 2011
// - Aaron Decker
$(function() {   
    // friendly helper http://tinyurl.com/6aow6yn
    $.fn.serializeObject = function() {
        var o = {};
        var a = this.serializeArray();
        $.each(a, function() {
            if (o[this.name]) {
                if (!o[this.name].push) {
                    o[this.name] = [o[this.name]];
                }
                o[this.name].push(this.value || '');
            } else {
                o[this.name] = this.value || '';
            }
        });
        return o;
    };

    var path = unescape(document.location.pathname).split('/'),
        design = path[3],
        db = $.couch.db(path[1]);

    // Various *pure* functions for use on this page
    var obj_to_table = function ( obj ) {
        var html = "";
        html += "<table id='table_id' class='display'>";
        html += "<thead><th>Category</th><th>Words</th></thead>";
        html += "<tbody>"
        var keys = Object.keys(obj)
        for(var i in keys ){
            var key = keys[i];
            if( key != '_id' && key != '_rev' ) {
                html+="<tr><th>" + key + "</th></tr>";
                for( var j in obj[key] ) {
                    html+="<tr><th></th><td>" + obj[key][j] + "</td></tr>";
                }
            }
        }
        html+="</tbody>";
        html+="</table>";
        return html;
    }

    // convert the table back into an object -- pretty hacky
    var table_to_obj = function ( table_selector ) {
        var obj = {};
        var rows = table_selector.find("tbody tr").toArray();
        var cur_key = null;
        for (var i in rows) {
            var new_key_maybe = $(rows[i]).find("th").html();
            if( new_key_maybe && new_key_maybe != "" ) {
                obj[new_key_maybe] = [];
                cur_key = new_key_maybe;
            }
            if( cur_key ) {
                var new_value_maybe = $(rows[i]).find("td").html();
                if( new_value_maybe ) {
                    obj[cur_key].push( new_value_maybe );
                }
            }
        }
        return obj;
    }

    // code that gets executed sequentially starts here
    var wordlist = {};
    var user_name = null;

/*    var temp = false;

    var test_promise = new Promise( function (resolve, reject) {
        console.log("eval'ing test_promise");
        if( temp == false ) {
            temp = true;
            resolve("foo");
        }
        error(temp);
    });
    
    test_promise.then( 
        function(response) {
            console.log("then'd (1a) to response: " + response);
            return new Promise( function (resolve, reject) {
                console.log("eval'ing second promise");
                resolve("bar");
                });
        },
        function(error) {
            console.log("then'd (1a) to error: " + error);
            return error;
        }).then(
            function(response) {
                console.log("then'd (1b) to response: " + response);
            },
            function(error) {
                console.log("then'd (1b) to error: " + error);
            }); 

    test_promise.then( 
        function(response) {
            console.log("then'd (2a) to response: " + response);
        },
        function(error) {
            console.log("then'd (2a) to error: " + error);
        });

    test_promise.then( function(response) { console.log("another: " + response); });*/

    var user_name_promise = new Promise( function (resolve, reject) {
        $.couch.session({
            success: function(data) {
                console.log(JSON.stringify(data));
                if( data.userCtx.name ) {
                    resolve(data.userCtx.name);
                }
                else {
                    reject();
                }
            }
        });
    });

    function openDoc_promise(docName) {
        return new Promise( function(resolve, reject) {
        db.openDoc(docName, {
            success : function (data) {
                resolve(data);
            },
            error : function (error) {
                reject(error);
            }});
        });
    }

/*    user_name_promise.then( 
        function(name) {console.log("***initial log in to user: "+ name)},
        function() {console.log("***user was not logged in on initial load.");});*/

    // load the wordlist 
    user_name_promise.then(
        function(name) { return openDoc_promise(name+"_wordlist"); },
        function() {console.log("===user was not logged in on initial load."); 
                   }).then(
                       function(wordlist) { console.log("===got user list: ", wordlist); },
                       function(error) { console.log("===user list does not exist"); });
                       

    var wordlist_promise = user_name_promise.then(
        function(name) { 
            console.log("+++need to open custom");
            db.openDoc(r.userCtx.name +"_wordlist", {
                success : function (data) {
                    console.log("+++opened custom: ",data);
                    return data;
                }})},
        function() {
            console.log("+++need to open generic");
        });

    $.couchProfile.templates.profileReady = $("#view-wordlist").html();
    $("#account").couchLogin({
        loggedIn : function(r) {
            console.log("logged in ", r);
            userCtx = r.userCtx.name;
            $("#profile").couchProfile(r, {
                profileReady : function(profile) {


                    
                    
                    var setup_table = function() {
                        var html = obj_to_table( wordlist );
                        $("#wordlist-customization-area").html( html );
                        $("#wordlist-customization-area>table").editableTableWidget();
                        $("#wordlist-customization-area>table td").on('change', function (evt, newValue) {
                            console.log("changed");
                            var new_wordlist = table_to_obj($("#table_id"));
                            new_wordlist._id = wordlist._id;
                            new_wordlist._rev = wordlist._rev;
                            db.saveDoc( 
                                new_wordlist,
                                {success: function(data) { 
                                    console.log("saved: ",data); 
                                    wordlist._rev = data.rev;
                                }}
                            );
                        });
                    }

                    if( using_default_wordlist ) {
                        db.openDoc(r.userCtx.name +"_wordlist", {
                            success : function (data) {
                                gotList = true;
                                wordlist = data;
                                using_default_wordlist = false;
                                setup_table();
                            },
                            error: function (data) {
                                wordlist._id = r.userCtx.name + "_wordlist";
                                delete wordlist._rev; // get server-assigned rev
                                db.saveDoc( wordlist, { success: function (data) {
                                    wordlist = data;
                                    using_default_wordlist = false;
                                    setup_table();
                                }});
                            }});
                    }
                    else {
                        setup_table();
                    }
                },
                loggedOut : function() {
                    console.log("logged out");
                    $("#profile").html('<p>Please log in to see your profile.</p>');
                }
            });
        }});

    function drawItems() {
        db.view(design + "/recent-items", {
            descending : "true",
            limit : 50,
            update_seq : true,
            success : function(data) {
                setupChanges(data.update_seq);
                var them = $.mustache($("#recent-messages").html(), {
                    items : data.rows.map(function(r) {return r.value;})
                });
                $("#content").html(them);
            }
        });
    };

    function pickWordsFromList( ) {
        var using_default_wordlist = false;
        
        var rand_elem = function( arr ) {
            var index = Math.floor( Math.random()*arr.length % arr.length );
            return arr[index];
        }
        // changes a word to uppercase
        var up = function( str ) {
            if( str ) {
                return str[0].toUpperCase() + str.substr(1);
            }
        }

        // pick a name
        var adj = up( rand_elem(wordlist.adjectives) );
        var subj = up( rand_elem(wordlist["subjects"]) );

        var template_data = {
            "name": adj + " " + subj + "&#0153;",
            "tasks": []
        };

        // generate the features
        for( var i = 0; i < 3; i++ ) {
            var verb = up( rand_elem( wordlist.verbs ) );
            var dir_obj = rand_elem( wordlist["direct-objects"] );
            var ind_obj = rand_elem( wordlist["indirect-objects"] );
            template_data.tasks.push({"task": verb + " " + dir_obj + " using " + ind_obj + "."});
        }

        $("#word_list").html(
            $.mustache($("#name-and-task").html(), template_data)
        );
        $("#word_list").find("#generate-new-enterprise-product").on(
            'click', function () {
                console.log("clicked");
                pickWordsFromList();
            });
                                                                     
    };

    // loads the wordlist and then calls the done_fn
    // passing in the wordlist as the argument
    function loadWordList(done_fn, user_name) {
        if( user_name ){
            db.openDoc(user_name +"_wordlist", {
                success : function (data) {
                    console.log("loaded user doc");
                    wordlist = data;
                    using_default_wordlist = false;
                    done_fn(wordlist);
                },
            error: function (data) {
                db.openDoc("software_wordlist", {
                success : function(data) {
                    console.log("loaded default doc (1)");
                    wordlist = data;
                    using_default_wordlist = true;
                    done_fn(wordlist);                
                }});
            }});
        }
        else {
            db.openDoc("software_wordlist", {
                success : function(data) {
                    console.log("loaded default doc (2)");
                    wordlist = data;
                    using_default_wordlist = true;
                    done_fn(wordlist);    
                }            
            });
        }

    };
    drawItems();
    loadWordList(pickWordsFromList, user_name);
//    var changesRunning = false;
/*    function setupChanges(since) {
        if (!changesRunning) {
            var changeHandler = db.changes(since);
            changesRunning = true;
            changeHandler.onChange(drawItems);
        }
    }*/
    
});
            
